# -*- coding: utf-8 -*-
"""Shap_PipeLine-v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15m04J6NWT_s7zs_xiZrATpgmrdrYOnWV

## SHAP 설명가능성 평가 파이프라인
이 노트북 하나에서 모델·감사 데이터 자동 탐색부터 SHAP, 민감변수 기여비율, 전역 설명 안정성, 설명 충실성, LIME 및 산출물 생성까지 실행합니다.
필요 입력 파일은 credit_model*.json, audit_dataset*.csv입니다.
"""
from __future__ import annotations

import json
import math
import os
import sys
import warnings
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable

os.environ.setdefault("MPLCONFIGDIR", str(Path.cwd() / ".matplotlib-cache"))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xgboost as xgb
from scipy.stats import spearmanr
from sklearn.metrics import roc_auc_score, r2_score


warnings.filterwarnings("ignore", category=FutureWarning)


DEFAULT_CONFIG: dict[str, Any] = {
    "target_column": "TARGET",
    "id_column": "SK_ID_CURR",
    "positive_class": 1,
    "top_k": 3,
    "random_seed": 42,
    "max_shap_rows": 5000,
    "max_permutation_rows": 3000,
    "permutation_repeats": 3,
    "stability_repeats": 10,
    "lime_cases": 5,
    "lime_num_samples": 1000,
    "thresholds": {
        "sensitive_contribution_ratio_max": 0.20,
        "sensitive_contribution_ratio_review_max": 0.30,
        "explanation_fidelity_min": 0.50,
        "explanation_fidelity_review_min": 0.30,
        "permutation_spearman_min": 0.50,
        "global_stability_spearman_min": 0.70,
        "global_stability_spearman_review_min": 0.50,
        "lime_overlap_min": 0.50,
        "additivity_max_abs_error_max": 0.0001,
    },
    "sensitive_groups": {
        "gender": ["CODE_GENDER", "GENDER"],
        "age": ["AGE", "AGE_GROUP", "DAYS_BIRTH"],
        "region": ["REGION"],
    },
    "disclosure_policy": {
        "default_model_feature_policy": "ALLOW",
        "sensitive_policy": "SENSITIVE",
        "deny_columns": ["SK_ID_CURR", "TARGET"],
        "review_patterns": ["SCORE", "INTERNAL", "CODE"],
    },
}


@dataclass
class RunContext:
    root: Path
    output: Path
    config: dict[str, Any]
    model: xgb.Booster
    raw: pd.DataFrame
    features: list[str]
    feature_types: list[str]
    X: pd.DataFrame
    y: pd.Series
    ids: pd.Series
    rng: np.random.Generator

def write_json(path: Path, obj: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2, default=json_default)


def json_default(value: Any) -> Any:
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return None if not np.isfinite(value) else float(value)
    if isinstance(value, (np.bool_,)):
        return bool(value)
    if isinstance(value, Path):
        return str(value)
    raise TypeError(f"Not JSON serializable: {type(value)}")


def make_dirs(output: Path) -> None:
    for name in ["summary", "global", "local", "sensitive", "validation", "figures", "metadata"]:
        (output / name).mkdir(parents=True, exist_ok=True)


def status_min(
    value: float | None,
    pass_threshold: float,
    review_threshold: float | None = None,
) -> str:
    if value is None or not np.isfinite(value):
        return "NOT_EVALUATED"
    if value >= pass_threshold:
        return "PASS"
    if review_threshold is not None and value < review_threshold:
        return "REVIEW"
    return "WARNING"


def status_max(
    value: float | None,
    pass_threshold: float,
    review_threshold: float | None = None,
) -> str:
    if value is None or not np.isfinite(value):
        return "NOT_EVALUATED"
    if value <= pass_threshold:
        return "PASS"
    if review_threshold is not None and value > review_threshold:
        return "REVIEW"
    return "WARNING"


def prepare_model_frame(raw: pd.DataFrame, features: list[str], feature_types: list[str]) -> pd.DataFrame:
    X = raw.loc[:, features].copy()
    for feature, ftype in zip(features, feature_types):
        if ftype == "c":
            X[feature] = X[feature].astype("category")
        elif ftype == "int":
            X[feature] = pd.to_numeric(X[feature], errors="coerce").astype("Int64")
        else:
            X[feature] = pd.to_numeric(X[feature], errors="coerce")
    return X


def make_dmatrix(X: pd.DataFrame, y: pd.Series | None = None) -> xgb.DMatrix:
    return xgb.DMatrix(X, label=y, enable_categorical=True, missing=np.nan)


def select_rows(ctx: RunContext, maximum: int) -> np.ndarray:
    n = len(ctx.X)
    size = min(maximum, n)
    return np.sort(ctx.rng.choice(n, size=size, replace=False))


def sensitive_feature_map(features: list[str], config: dict[str, Any]) -> pd.DataFrame:
    rows: list[dict[str, Any]] = []
    groups: dict[str, list[str]] = config["sensitive_groups"]
    policy = config["disclosure_policy"]
    review_patterns = [x.upper() for x in policy.get("review_patterns", [])]
    for feature in features:
        upper = feature.upper()
        matched_groups = [
            group
            for group, patterns in groups.items()
            if any(pattern.upper() in upper for pattern in patterns)
        ]
        sensitive_group = ",".join(matched_groups)
        if matched_groups:
            disclosure = policy.get("sensitive_policy", "SENSITIVE")
            action = "EXCLUDE"
        elif any(pattern in upper for pattern in review_patterns):
            disclosure = "REVIEW"
            action = "REVIEW"
        else:
            disclosure = policy.get("default_model_feature_policy", "ALLOW")
            action = "INCLUDE" if disclosure == "ALLOW" else "EXCLUDE"
        rows.append(
            {
                "feature": feature,
                "sensitive_group": sensitive_group,
                "is_sensitive": bool(matched_groups),
                "disclosure_policy": disclosure,
                "action": action,
            }
        )
    return pd.DataFrame(rows)


def schema_validation(
    raw: pd.DataFrame,
    model: xgb.Booster,
    config: dict[str, Any],
) -> tuple[dict[str, Any], list[str], list[str]]:
    features = model.feature_names or []
    feature_types = model.feature_types or ["float"] * len(features)
    missing = [f for f in features if f not in raw.columns]
    required = [config["target_column"], config["id_column"]]
    missing_required = [f for f in required if f not in raw.columns]
    duplicate_columns = raw.columns[raw.columns.duplicated()].tolist()
    extra = [f for f in raw.columns if f not in features and f not in required]
    result = {
        "status": "PASS" if not missing and not missing_required and not duplicate_columns else "FAIL",
        "model_feature_count": len(features),
        "dataset_column_count": len(raw.columns),
        "row_count": len(raw),
        "missing_model_features": missing,
        "missing_required_columns": missing_required,
        "duplicate_columns": duplicate_columns,
        "audit_only_columns": extra,
    }
    return result, features, feature_types


def shap_calculation(ctx: RunContext) -> dict[str, Any]:
    rows = select_rows(ctx, int(ctx.config["max_shap_rows"]))
    Xs = ctx.X.iloc[rows]
    ys = ctx.y.iloc[rows]
    ids = ctx.ids.iloc[rows].reset_index(drop=True)
    dm = make_dmatrix(Xs, ys)
    pred_probability = ctx.model.predict(dm)
    pred_margin = ctx.model.predict(dm, output_margin=True)
    contributions = ctx.model.predict(dm, pred_contribs=True)
    shap_values = contributions[:, :-1]
    base_values = contributions[:, -1]
    reconstructed = base_values + shap_values.sum(axis=1)
    errors = np.abs(pred_margin - reconstructed)
    additivity = pd.DataFrame(
        {
            "customer_id": ids,
            "prediction_probability": pred_probability,
            "model_margin": pred_margin,
            "shap_reconstructed_margin": reconstructed,
            "absolute_error": errors,
        }
    )
    additivity.to_csv(ctx.output / "validation" / "additivity_validation.csv", index=False, encoding="utf-8-sig")
    threshold = ctx.config["thresholds"]["additivity_max_abs_error_max"]
    additivity_summary = {
        "sample_size": len(rows),
        "mean_absolute_error": float(errors.mean()),
        "max_absolute_error": float(errors.max()),
        "threshold": threshold,
        "status": status_max(float(errors.max()), threshold),
    }
    write_json(ctx.output / "validation" / "additivity_summary.json", additivity_summary)
    return {
        "row_indices": rows,
        "X": Xs,
        "y": ys,
        "ids": ids,
        "pred_probability": pred_probability,
        "pred_margin": pred_margin,
        "shap_values": shap_values,
        "base_values": base_values,
        "additivity": additivity_summary,
    }


def global_importance(ctx: RunContext, shap_result: dict[str, Any], mapping: pd.DataFrame) -> pd.DataFrame:
    values = shap_result["shap_values"]
    mean_abs = np.abs(values).mean(axis=0)
    signed_mean = values.mean(axis=0)
    total = mean_abs.sum()
    result = pd.DataFrame(
        {
            "feature": ctx.features,
            "mean_abs_shap": mean_abs,
            "mean_signed_shap": signed_mean,
            "contribution_ratio": mean_abs / total if total else np.nan,
        }
    ).merge(mapping, on="feature", how="left")
    result = result.sort_values("mean_abs_shap", ascending=False).reset_index(drop=True)
    result.insert(0, "rank", np.arange(1, len(result) + 1))
    result.to_csv(ctx.output / "global" / "global_shap_importance.csv", index=False, encoding="utf-8-sig")
    return result


def create_raw_local(ctx: RunContext, shap_result: dict[str, Any], mapping: pd.DataFrame) -> pd.DataFrame:
    policy_lookup = mapping.set_index("feature").to_dict("index")
    rows: list[dict[str, Any]] = []
    values = shap_result["shap_values"]
    Xs = shap_result["X"].reset_index(drop=True)
    for i in range(len(Xs)):
        order = np.argsort(-np.abs(values[i]))
        for rank, j in enumerate(order, start=1):
            feature = ctx.features[j]
            info = policy_lookup[feature]
            rows.append(
                {
                    "customer_id": shap_result["ids"].iloc[i],
                    "prediction_probability": shap_result["pred_probability"][i],
                    "rank": rank,
                    "feature": feature,
                    "feature_value": Xs.iloc[i, j],
                    "shap_value": values[i, j],
                    "direction": "RISK_INCREASE" if values[i, j] > 0 else "RISK_DECREASE",
                    "is_sensitive": info["is_sensitive"],
                    "sensitive_group": info["sensitive_group"],
                    "disclosure_policy": info["disclosure_policy"],
                }
            )
    result = pd.DataFrame(rows)
    result.to_csv(ctx.output / "local" / "customer_raw_explanations.csv", index=False, encoding="utf-8-sig")
    return result


def permutation_validation(ctx: RunContext, global_df: pd.DataFrame) -> tuple[pd.DataFrame, dict[str, Any]]:
    indices = select_rows(ctx, int(ctx.config["max_permutation_rows"]))
    Xp = ctx.X.iloc[indices].copy()
    yp = ctx.y.iloc[indices].to_numpy()
    baseline = ctx.model.predict(make_dmatrix(Xp))
    baseline_auc = roc_auc_score(yp, baseline)
    repeats = int(ctx.config["permutation_repeats"])
    rows = []
    feature_type_lookup = dict(zip(ctx.features, ctx.feature_types))
    for feature in ctx.features:
        drops = []
        for _ in range(repeats):
            shuffled = Xp.copy()
            if feature_type_lookup[feature] == "c":
                permuted = ctx.rng.permutation(shuffled[feature].astype(object).to_numpy())
                shuffled[feature] = pd.Categorical(permuted, categories=Xp[feature].cat.categories)
            else:
                permuted = ctx.rng.permutation(shuffled[feature].to_numpy())
                shuffled[feature] = permuted
            pred = ctx.model.predict(make_dmatrix(shuffled))
            drops.append(baseline_auc - roc_auc_score(yp, pred))
        rows.append({"feature": feature, "permutation_auc_drop": float(np.mean(drops))})
    result = pd.DataFrame(rows).sort_values("permutation_auc_drop", ascending=False).reset_index(drop=True)
    result.insert(0, "permutation_rank", np.arange(1, len(result) + 1))
    result = result.merge(global_df[["feature", "rank", "mean_abs_shap"]], on="feature", how="left")
    result = result.rename(columns={"rank": "shap_rank"})
    result["rank_difference"] = (result["permutation_rank"] - result["shap_rank"]).abs()
    corr = spearmanr(result["shap_rank"], result["permutation_rank"]).statistic
    k = min(20, len(result))
    shap_top = set(result.nsmallest(k, "shap_rank")["feature"])
    perm_top = set(result.nsmallest(k, "permutation_rank")["feature"])
    jaccard = len(shap_top & perm_top) / len(shap_top | perm_top)
    summary = {
        "sample_size": len(indices),
        "baseline_auc": float(baseline_auc),
        "spearman": float(corr),
        "top20_jaccard": float(jaccard),
        "status": status_min(float(corr), ctx.config["thresholds"]["permutation_spearman_min"]),
    }
    result.to_csv(ctx.output / "global" / "permutation_comparison.csv", index=False, encoding="utf-8-sig")
    write_json(ctx.output / "global" / "permutation_summary.json", summary)
    return result, summary


def global_stability(ctx: RunContext, shap_result: dict[str, Any]) -> tuple[pd.DataFrame, dict[str, Any]]:
    values = np.abs(shap_result["shap_values"])
    n = len(values)
    repeats = int(ctx.config["stability_repeats"])
    run_ranks = []
    reference = values.mean(axis=0)
    ref_rank = pd.Series(-reference).rank(method="average").to_numpy()
    correlations = []
    jaccards = []
    k = min(20, len(ctx.features))
    ref_top = set(np.argsort(-reference)[:k])
    for run in range(repeats):
        sampled = ctx.rng.choice(n, size=n, replace=True)
        importance = values[sampled].mean(axis=0)
        ranks = pd.Series(-importance).rank(method="average").to_numpy()
        run_ranks.append(ranks)
        correlations.append(spearmanr(ref_rank, ranks).statistic)
        top = set(np.argsort(-importance)[:k])
        jaccards.append(len(ref_top & top) / len(ref_top | top))
    ranks_matrix = np.vstack(run_ranks)
    detail = pd.DataFrame(
        {
            "feature": ctx.features,
            "mean_rank": ranks_matrix.mean(axis=0),
            "rank_std": ranks_matrix.std(axis=0),
            "top20_inclusion_rate": (ranks_matrix <= k).mean(axis=0),
        }
    ).sort_values("mean_rank")
    summary = {
        "repeats": repeats,
        "mean_spearman": float(np.mean(correlations)),
        "mean_top20_jaccard": float(np.mean(jaccards)),
        "review_threshold": ctx.config["thresholds"][
            "global_stability_spearman_review_min"
        ],
        "status": status_min(
            float(np.mean(correlations)),
            ctx.config["thresholds"]["global_stability_spearman_min"],
            ctx.config["thresholds"]["global_stability_spearman_review_min"],
        ),
    }
    detail.to_csv(ctx.output / "global" / "global_stability.csv", index=False, encoding="utf-8-sig")
    write_json(ctx.output / "global" / "global_stability_summary.json", summary)
    return detail, summary


def sensitive_audit(
    ctx: RunContext,
    shap_result: dict[str, Any],
    mapping: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, dict[str, Any]]:
    values = np.abs(shap_result["shap_values"])
    total = values.sum()
    rows = []
    sensitive_mask = mapping["is_sensitive"].to_numpy(dtype=bool)
    for group in ctx.config["sensitive_groups"]:
        group_mask = mapping["sensitive_group"].fillna("").str.split(",").apply(lambda x: group in x).to_numpy()
        group_sum = values[:, group_mask].sum() if group_mask.any() else 0.0
        rows.append(
            {
                "sensitive_group": group,
                "model_features": ",".join(mapping.loc[group_mask, "feature"]),
                "abs_shap_sum": group_sum,
                "contribution_ratio": group_sum / total if total else np.nan,
                "directly_used_by_model": bool(group_mask.any()),
            }
        )
    detail = pd.DataFrame(rows)
    sensitive_total = values[:, sensitive_mask].sum() if sensitive_mask.any() else 0.0
    ratio = sensitive_total / total if total else np.nan
    threshold = ctx.config["thresholds"]["sensitive_contribution_ratio_max"]
    review_threshold = ctx.config["thresholds"][
        "sensitive_contribution_ratio_review_max"
    ]
    summary = {
        "value": float(ratio),
        "threshold": threshold,
        "review_threshold": review_threshold,
        "status": status_max(
            float(ratio),
            threshold,
            review_threshold,
        ),
        "note": "Direct SHAP contribution of model-input sensitive feature families only; proxy effects are not measured.",
    }
    detail.to_csv(ctx.output / "sensitive" / "sensitive_feature_audit.csv", index=False, encoding="utf-8-sig")

    per_customer_total = values.sum(axis=1)
    per_customer_sensitive = values[:, sensitive_mask].sum(axis=1) if sensitive_mask.any() else np.zeros(len(values))
    per_customer_ratio = np.divide(
        per_customer_sensitive,
        per_customer_total,
        out=np.zeros_like(per_customer_sensitive),
        where=per_customer_total != 0,
    )
    audit = ctx.raw.iloc[shap_result["row_indices"]].reset_index(drop=True)
    group_rows: list[dict[str, Any]] = []
    for group_column in ["CODE_GENDER", "AGE_GROUP"]:
        if group_column not in audit.columns:
            continue
        temp = pd.DataFrame({"group": audit[group_column].astype(str), "ratio": per_customer_ratio})
        for group_value, frame in temp.groupby("group", dropna=False):
            group_rows.append(
                {
                    "group_column": group_column,
                    "group_value": group_value,
                    "customer_count": len(frame),
                    "mean_sensitive_ratio": frame["ratio"].mean(),
                    "median_sensitive_ratio": frame["ratio"].median(),
                    "p95_sensitive_ratio": frame["ratio"].quantile(0.95),
                }
            )
    group_detail = pd.DataFrame(group_rows)
    group_detail.to_csv(ctx.output / "sensitive" / "sensitive_group_audit.csv", index=False, encoding="utf-8-sig")
    write_json(ctx.output / "sensitive" / "sensitive_summary.json", summary)
    return detail, group_detail, summary


def apply_policy_and_fidelity(
    ctx: RunContext,
    shap_result: dict[str, Any],
    mapping: pd.DataFrame,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, dict[str, Any]]:
    include = mapping["action"].eq("INCLUDE").to_numpy()
    policy_lookup = mapping.set_index("feature").to_dict("index")
    values = shap_result["shap_values"]
    Xs = shap_result["X"].reset_index(drop=True)
    top_k = int(ctx.config["top_k"])
    final_rows = []
    filter_rows = []
    fidelity_rows = []
    for i in range(len(Xs)):
        allowed_indices = np.where(include)[0]
        allowed_order = allowed_indices[np.argsort(-np.abs(values[i, allowed_indices]))]
        chosen = allowed_order[:top_k]
        raw_top = np.argsort(-np.abs(values[i]))[:top_k]
        for j in raw_top:
            info = policy_lookup[ctx.features[j]]
            filter_rows.append(
                {
                    "customer_id": shap_result["ids"].iloc[i],
                    "feature": ctx.features[j],
                    "original_top_k": True,
                    "action": info["action"],
                    "reason": info["disclosure_policy"],
                }
            )
        for rank, j in enumerate(chosen, start=1):
            final_rows.append(
                {
                    "customer_id": shap_result["ids"].iloc[i],
                    "prediction_probability": shap_result["pred_probability"][i],
                    "rank": rank,
                    "feature": ctx.features[j],
                    "feature_value": Xs.iloc[i, j],
                    "shap_value": values[i, j],
                    "direction": "RISK_INCREASE" if values[i, j] > 0 else "RISK_DECREASE",
                }
            )
        all_abs = np.abs(values[i]).sum()
        selected_abs = np.abs(values[i, chosen]).sum()
        coverage = selected_abs / all_abs if all_abs else 1.0
        reconstructed = shap_result["base_values"][i] + values[i, chosen].sum()
        fidelity_rows.append(
            {
                "customer_id": shap_result["ids"].iloc[i],
                "model_margin": shap_result["pred_margin"][i],
                "explanation_reconstructed_margin": reconstructed,
                "absolute_margin_error": abs(shap_result["pred_margin"][i] - reconstructed),
                "absolute_contribution_coverage": coverage,
                "selected_reason_count": len(chosen),
            }
        )
    final_df = pd.DataFrame(final_rows)
    filter_df = pd.DataFrame(filter_rows)
    fidelity_df = pd.DataFrame(fidelity_rows)
    fidelity_value = float(fidelity_df["absolute_contribution_coverage"].median())
    r2 = r2_score(fidelity_df["model_margin"], fidelity_df["explanation_reconstructed_margin"])
    summary = {
        "value": fidelity_value,
        "metric": "median_absolute_contribution_coverage",
        "threshold": ctx.config["thresholds"]["explanation_fidelity_min"],
        "review_threshold": ctx.config["thresholds"][
            "explanation_fidelity_review_min"
        ],
        "status": status_min(
            fidelity_value,
            ctx.config["thresholds"]["explanation_fidelity_min"],
            ctx.config["thresholds"]["explanation_fidelity_review_min"],
        ),
        "margin_reconstruction_r2": float(r2),
        "margin_reconstruction_mae": float(fidelity_df["absolute_margin_error"].mean()),
        "top_k": top_k,
    }
    final_df.to_csv(ctx.output / "local" / "customer_final_explanations.csv", index=False, encoding="utf-8-sig")
    filter_df.to_csv(ctx.output / "validation" / "policy_filter_log.csv", index=False, encoding="utf-8-sig")
    fidelity_df.to_csv(ctx.output / "local" / "customer_fidelity.csv", index=False, encoding="utf-8-sig")
    write_json(ctx.output / "local" / "fidelity_summary.json", summary)
    return final_df, filter_df, fidelity_df, summary


def lime_validation(
    ctx: RunContext,
    shap_result: dict[str, Any],
) -> tuple[pd.DataFrame, dict[str, Any]]:
    try:
        from lime.lime_tabular import LimeTabularExplainer
    except Exception as exc:
        summary = {"status": "NOT_EVALUATED", "reason": f"LIME import failed: {exc}"}
        write_json(ctx.output / "local" / "lime_summary.json", summary)
        return pd.DataFrame(), summary

    Xs = shap_result["X"].reset_index(drop=True)
    encoded = pd.DataFrame(index=Xs.index)
    categorical_indices = []
    categorical_names: dict[int, list[str]] = {}
    category_levels: dict[str, list[Any]] = {}
    fill_values: dict[str, float] = {}
    for j, (feature, ftype) in enumerate(zip(ctx.features, ctx.feature_types)):
        if ftype == "c":
            categorical_indices.append(j)
            levels = list(Xs[feature].cat.categories)
            category_levels[feature] = levels
            categorical_names[j] = [str(v) for v in levels]
            codes = Xs[feature].cat.codes.replace(-1, np.nan).astype(float)
            mode = codes.mode()
            fill = float(mode.iloc[0]) if not mode.empty else 0.0
            fill_values[feature] = fill
            encoded[feature] = codes.fillna(fill)
        else:
            series = pd.to_numeric(Xs[feature], errors="coerce").astype(float)
            fill = float(series.median()) if series.notna().any() else 0.0
            fill_values[feature] = fill
            encoded[feature] = series.fillna(fill)

    def predict_fn(array: np.ndarray) -> np.ndarray:
        frame = pd.DataFrame(array, columns=ctx.features)
        for j, (feature, ftype) in enumerate(zip(ctx.features, ctx.feature_types)):
            if ftype == "c":
                levels = category_levels[feature]
                codes = np.clip(np.rint(frame[feature]).astype(int), 0, max(len(levels) - 1, 0))
                frame[feature] = pd.Categorical.from_codes(codes, categories=levels)
            elif ftype == "int":
                frame[feature] = pd.to_numeric(frame[feature], errors="coerce").round().astype("Int64")
            else:
                frame[feature] = pd.to_numeric(frame[feature], errors="coerce")
        probability = ctx.model.predict(make_dmatrix(frame))
        return np.column_stack([1.0 - probability, probability])

    explainer = LimeTabularExplainer(
        encoded.to_numpy(dtype=float),
        feature_names=ctx.features,
        class_names=["low_risk", "high_risk"],
        categorical_features=categorical_indices,
        categorical_names=categorical_names,
        discretize_continuous=True,
        random_state=int(ctx.config["random_seed"]),
        mode="classification",
    )
    case_count = min(int(ctx.config["lime_cases"]), len(Xs))
    probabilities = shap_result["pred_probability"]
    candidate_indices = list(dict.fromkeys([int(np.argmax(probabilities)), int(np.argmin(probabilities)), int(np.argmin(np.abs(probabilities - 0.5)))]))
    remaining = [i for i in range(len(Xs)) if i not in candidate_indices]
    if len(candidate_indices) < case_count:
        candidate_indices.extend(ctx.rng.choice(remaining, size=case_count - len(candidate_indices), replace=False).tolist())
    rows = []
    top_k = int(ctx.config["top_k"])
    for i in candidate_indices[:case_count]:
        explanation = explainer.explain_instance(
            encoded.iloc[i].to_numpy(dtype=float),
            predict_fn,
            labels=(1,),
            num_features=top_k,
            num_samples=int(ctx.config["lime_num_samples"]),
        )
        lime_features = {ctx.features[idx] for idx, _ in explanation.as_map().get(1, [])}
        shap_top_idx = np.argsort(-np.abs(shap_result["shap_values"][i]))[:top_k]
        shap_features = {ctx.features[idx] for idx in shap_top_idx}
        union = lime_features | shap_features
        overlap = len(lime_features & shap_features) / len(union) if union else 1.0
        rows.append(
            {
                "customer_id": shap_result["ids"].iloc[i],
                "prediction_probability": probabilities[i],
                "shap_top_features": ",".join(sorted(shap_features)),
                "lime_top_features": ",".join(sorted(lime_features)),
                "top_k_jaccard": overlap,
                "lime_local_r2": float(explanation.score),
            }
        )
    detail = pd.DataFrame(rows)
    mean_overlap = float(detail["top_k_jaccard"].mean()) if not detail.empty else np.nan
    summary = {
        "case_count": len(detail),
        "mean_top_k_jaccard": mean_overlap,
        "status": status_min(mean_overlap, ctx.config["thresholds"]["lime_overlap_min"]),
        "note": "LIME is a sampled local surrogate and is used only as a supplementary check.",
    }
    detail.to_csv(ctx.output / "local" / "lime_validation.csv", index=False, encoding="utf-8-sig")
    write_json(ctx.output / "local" / "lime_summary.json", summary)
    return detail, summary


def create_figures(
    ctx: RunContext,
    global_df: pd.DataFrame,
    permutation_df: pd.DataFrame,
    sensitive_df: pd.DataFrame,
    fidelity_df: pd.DataFrame,
    kpis: list[dict[str, Any]],
) -> None:
    plt.rcParams.update({"figure.dpi": 130, "axes.grid": True, "grid.alpha": 0.2})
    top = global_df.head(20).sort_values("mean_abs_shap")
    fig, ax = plt.subplots(figsize=(9, 6))
    ax.barh(top["feature"], top["mean_abs_shap"], color="#4caf68")
    ax.set_title("Global SHAP importance: Top 20")
    ax.set_xlabel("Mean |SHAP| (margin)")
    fig.tight_layout()
    fig.savefig(ctx.output / "figures" / "global_shap_top20.png", bbox_inches="tight")
    plt.close(fig)

    merged = permutation_df.nsmallest(20, "shap_rank")
    fig, ax = plt.subplots(figsize=(7, 6))
    ax.scatter(merged["mean_abs_shap"], merged["permutation_auc_drop"], color="#2f66e9")
    for _, row in merged.head(10).iterrows():
        ax.annotate(row["feature"], (row["mean_abs_shap"], row["permutation_auc_drop"]), fontsize=7)
    ax.set_title("SHAP vs permutation importance")
    ax.set_xlabel("Mean |SHAP|")
    ax.set_ylabel("AUC drop")
    fig.tight_layout()
    fig.savefig(ctx.output / "figures" / "permutation_vs_shap.png", bbox_inches="tight")
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(7, 4))
    ax.bar(sensitive_df["sensitive_group"], sensitive_df["contribution_ratio"], color="#e9a72f")
    ax.set_title("Sensitive feature contribution ratio")
    ax.set_ylabel("Ratio of total |SHAP|")
    ax.set_ylim(bottom=0)
    fig.tight_layout()
    fig.savefig(ctx.output / "figures" / "sensitive_contribution.png", bbox_inches="tight")
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(7, 4))
    ax.hist(fidelity_df["absolute_contribution_coverage"], bins=20, color="#2ca66f", edgecolor="white")
    ax.axvline(ctx.config["thresholds"]["explanation_fidelity_min"], color="red", linestyle="--")
    ax.set_title("Customer explanation fidelity")
    ax.set_xlabel("Top-K absolute contribution coverage")
    fig.tight_layout()
    fig.savefig(ctx.output / "figures" / "fidelity_distribution.png", bbox_inches="tight")
    plt.close(fig)

    fig, axes = plt.subplots(1, 3, figsize=(12, 3.2))
    for ax, item in zip(axes, kpis):
        value = item["value"]
        if value is None:
            display = "N/A"
        elif item["metric"] == "sensitive_contribution_ratio":
            display = f"{value:.2%}"
        elif item["metric"] == "global_explanation_stability":
            display = f"{value:.4f}"
        else:
            display = f"{value:.3f}"
        color = {
            "PASS": "#23a56a",
            "WARNING": "#92400E",
            "REVIEW": "#B91C1C",
            "NOT_EVALUATED": "#8992a3",
        }.get(item["status"], "#8992a3")
        ax.axis("off")
        ax.text(0.05, 0.75, item["label"], fontsize=11, transform=ax.transAxes)
        ax.text(0.05, 0.42, display, fontsize=22, fontweight="bold", transform=ax.transAxes)
        ax.text(0.05, 0.12, item["status"], color="white", bbox={"boxstyle": "round,pad=0.4", "facecolor": color, "edgecolor": color}, transform=ax.transAxes)
    fig.suptitle("Explainability KPI dashboard", fontweight="bold")
    fig.tight_layout()
    fig.savefig(ctx.output / "figures" / "explainability_dashboard.png", bbox_inches="tight")
    plt.close(fig)


def overall_status(statuses: list[str]) -> str:
    evaluated = [s for s in statuses if s != "NOT_EVALUATED"]
    if not evaluated:
        return "NOT_EVALUATED"
    if "REVIEW" in evaluated:
        return "REVIEW"
    if "WARNING" in evaluated or "NOT_EVALUATED" in statuses:
        return "WARNING"
    return "PASS"


def _finite_or_none(value: Any) -> float | None:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return None
    return number if math.isfinite(number) else None


def build_report_payload(
    global_df: pd.DataFrame,
    schema: dict[str, Any],
    sensitive_summary: dict[str, Any],
    stability_summary: dict[str, Any],
    fidelity_summary: dict[str, Any],
    permutation_summary: dict[str, Any],
    additivity_summary: dict[str, Any],
    manifest_meta: dict[str, str],
    config: dict[str, Any],
    audit_sample_size: int,
    dataset_row_count: int,
) -> dict[str, Any]:
    """이미 계산된 프레임·요약을 리포트용 구조화 payload 로 재조립한다.

    새 계산은 하지 않는다. 전역중요도는 상위 `report_top_n` 만 인라인으로 담고,
    전체는 산출물 CSV 로 남는다.
    """
    thresholds = config["thresholds"]
    top_n = int(config.get("report_top_n", 20))
    top = global_df.head(top_n)

    global_importance_top = [
        {
            "rank": int(row["rank"]),
            "feature": str(row["feature"]),
            "mean_abs_shap": float(row["mean_abs_shap"]),
            "mean_signed_shap": float(row["mean_signed_shap"]),
            "contribution_ratio": _finite_or_none(row["contribution_ratio"]),
            "direction": (
                "RISK_INCREASE"
                if float(row["mean_signed_shap"]) > 0
                else "RISK_DECREASE"
            ),
            "is_sensitive": bool(row["is_sensitive"]),
            "sensitive_group": (
                (str(row["sensitive_group"]) or None)
                if pd.notna(row.get("sensitive_group"))
                else None
            ),
        }
        for _, row in top.iterrows()
    ]

    metrics = [
        {
            "metric": "GLOBAL_STABILITY",
            "value": _finite_or_none(stability_summary["mean_spearman"]),
            "threshold": thresholds["global_stability_spearman_min"],
            "review_threshold": thresholds["global_stability_spearman_review_min"],
            "status": stability_summary["status"],
            "extra": {
                "mean_top20_jaccard": float(stability_summary["mean_top20_jaccard"]),
                "repeats": float(stability_summary["repeats"]),
            },
        },
        {
            "metric": "FIDELITY",
            "value": _finite_or_none(fidelity_summary["value"]),
            "threshold": thresholds["explanation_fidelity_min"],
            "review_threshold": thresholds["explanation_fidelity_review_min"],
            "status": fidelity_summary["status"],
            "extra": {
                "margin_reconstruction_r2": float(
                    fidelity_summary["margin_reconstruction_r2"]
                ),
                "margin_reconstruction_mae": float(
                    fidelity_summary["margin_reconstruction_mae"]
                ),
                "top_k": float(fidelity_summary["top_k"]),
            },
        },
        {
            "metric": "SENSITIVE_CONTRIB",
            "value": _finite_or_none(sensitive_summary["value"]),
            "threshold": sensitive_summary["threshold"],
            "review_threshold": sensitive_summary["review_threshold"],
            "status": sensitive_summary["status"],
            "extra": {},
        },
        {
            "metric": "SHAP_ADDITIVITY",
            "value": _finite_or_none(additivity_summary["max_absolute_error"]),
            "threshold": additivity_summary["threshold"],
            "review_threshold": None,
            "status": additivity_summary["status"],
            "extra": {
                "mean_absolute_error": float(additivity_summary["mean_absolute_error"]),
                "sample_size": float(additivity_summary["sample_size"]),
            },
        },
        {
            "metric": "PERMUTATION_ALIGNMENT",
            "value": _finite_or_none(permutation_summary["spearman"]),
            "threshold": thresholds["permutation_spearman_min"],
            "review_threshold": None,
            "status": permutation_summary["status"],
            "extra": {
                "top20_jaccard": float(permutation_summary["top20_jaccard"]),
                "baseline_auc": float(permutation_summary["baseline_auc"]),
                "sample_size": float(permutation_summary["sample_size"]),
            },
        },
    ]

    schema_validation = {
        "status": schema["status"],
        "row_count": int(schema["row_count"]),
        "model_feature_count": int(schema["model_feature_count"]),
        "dataset_column_count": int(schema["dataset_column_count"]),
        "missing_model_features": list(schema["missing_model_features"]),
        "missing_required_columns": list(schema["missing_required_columns"]),
        "duplicate_columns": list(schema["duplicate_columns"]),
        "audit_only_columns": list(schema["audit_only_columns"]),
    }

    sampling = {
        "audit_sample_size": float(audit_sample_size),
        "dataset_row_count": float(dataset_row_count),
        "max_shap_rows": float(config["max_shap_rows"]),
        "max_permutation_rows": float(config["max_permutation_rows"]),
        "permutation_repeats": float(config["permutation_repeats"]),
        "stability_repeats": float(config["stability_repeats"]),
        "random_seed": float(config["random_seed"]),
        "report_top_n": float(top_n),
    }

    return {
        "schema_validation": schema_validation,
        "metrics": metrics,
        "global_importance_top": global_importance_top,
        "sampling": sampling,
        "thresholds": {key: float(value) for key, value in thresholds.items()},
        "manifest": dict(manifest_meta),
        "limitations": [],
    }


def run_shap_pipeline(
    model_path: Path,
    data_path: Path,
    output: Path,
    config: dict[str, Any],
    skip_lime: bool = True,
) -> dict[str, Any]:
    """지정된 모델과 데이터로 SHAP 분석을 실행하고 요약 결과를 반환한다."""

    root = Path.cwd()
    model_path = Path(model_path).expanduser().resolve()
    data_path = Path(data_path).expanduser().resolve()
    output = Path(output).expanduser().resolve()

    if not model_path.is_file():
        raise FileNotFoundError(f"모델 파일을 찾을 수 없습니다: {model_path}")

    if not data_path.is_file():
        raise FileNotFoundError(f"감사 데이터셋을 찾을 수 없습니다: {data_path}")

    config = json.loads(json.dumps(config))
    make_dirs(output)
    write_json(
        output / "metadata" / "effective_config.json",
        config,
    )

    model = xgb.Booster()
    model.load_model(model_path)
    raw = pd.read_csv(data_path)
    schema, features, feature_types = schema_validation(raw, model, config)
    write_json(output / "validation" / "schema_validation.json", schema)
    if schema["status"] != "PASS":
            raise ValueError(
                "SHAP 입력 스키마 검증 실패: "
                + json.dumps(schema, ensure_ascii=False)
            )

    X = prepare_model_frame(raw, features, feature_types)
    y = pd.to_numeric(raw[config["target_column"]], errors="raise").astype(int)
    ids = raw[config["id_column"]]
    ctx = RunContext(
        root=root,
        output=output,
        config=config,
        model=model,
        raw=raw,
        features=features,
        feature_types=feature_types,
        X=X,
        y=y,
        ids=ids,
        rng=np.random.default_rng(int(config["random_seed"])),
    )

    mapping = sensitive_feature_map(features, config)
    mapping.to_csv(output / "validation" / "feature_policy_map.csv", index=False, encoding="utf-8-sig")
    shap_result = shap_calculation(ctx)
    global_df = global_importance(ctx, shap_result, mapping)
    create_raw_local(ctx, shap_result, mapping)
    permutation_df, permutation_summary = permutation_validation(ctx, global_df)
    _, stability_summary = global_stability(ctx, shap_result)
    sensitive_df, _, sensitive_summary = sensitive_audit(ctx, shap_result, mapping)
    _, _, fidelity_df, fidelity_summary = apply_policy_and_fidelity(ctx, shap_result, mapping)
    if skip_lime:
        lime_summary = {"status": "NOT_EVALUATED", "reason": "Skipped by command-line option"}
        write_json(output / "local" / "lime_summary.json", lime_summary)
    else:
        _, lime_summary = lime_validation(ctx, shap_result)

    kpis = [
        {
            "metric": "sensitive_contribution_ratio",
            "label": "Sensitive contribution ratio",
            "value": sensitive_summary["value"],
            "threshold": sensitive_summary["threshold"],
            "review_threshold": sensitive_summary["review_threshold"],
            "status": sensitive_summary["status"],
        },
        {
            "metric": "global_explanation_stability",
            "label": "Global explanation stability",
            "value": stability_summary["mean_spearman"],
            "threshold": config["thresholds"]["global_stability_spearman_min"],
            "review_threshold": stability_summary["review_threshold"],
            "status": stability_summary["status"],
        },
        {
            "metric": "explanation_fidelity",
            "label": "Explanation fidelity",
            "value": fidelity_summary["value"],
            "threshold": fidelity_summary["threshold"],
            "review_threshold": fidelity_summary["review_threshold"],
            "status": fidelity_summary["status"],
        },
    ]
    pd.DataFrame(kpis).to_csv(output / "summary" / "explainability_kpi.csv", index=False, encoding="utf-8-sig")
    core_statuses = [item["status"] for item in kpis]
    summary = {
        "pipeline_status": "COMPLETED",
        "overall_status": overall_status(core_statuses),
        "audit_sample_size": len(shap_result["ids"]),
        "dataset_row_count": len(raw),
        "model_feature_count": len(features),
        "key_metrics": {item["metric"]: item for item in kpis},
        "supporting_checks": {
            "schema_validation": schema["status"],
            "shap_additivity": shap_result["additivity"]["status"],
            "permutation_alignment": permutation_summary["status"],
            "global_stability": stability_summary["status"],
            "lime_alignment": lime_summary["status"],
        },
        "limitations": [
            (
                "전역 설명 안정성은 감사 표본 내 설명의 강건성을 측정하며, "
                "재학습된 모델 간 일관성을 의미하지 않습니다."
            ),
            (
                "민감변수 기여도는 매핑된 모델 입력변수의 직접적인 사용 정도를 "
                "측정하며, 대리변수를 통한 차별 가능성은 평가 범위에 포함되지 "
                "않습니다."
            ),
            (
                "SHAP과 LIME은 모델 예측과 입력변수 간의 연관성을 설명하며, "
                "인과관계를 입증하지 않습니다."
            ),
            (
                "정보 공개 정책은 초기 기준이며, 실제 고객 대상 적용 전 "
                "도메인 및 법률 전문가의 검토가 필요합니다."
            ),
        ],
    }
    write_json(output / "summary" / "explainability_summary.json", summary)
    create_figures(ctx, global_df, permutation_df, sensitive_df, fidelity_df, kpis)

    manifest_meta = {
        "run_id": f"shap_audit_{datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ')}",
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "model_file": model_path.name,
        "data_file": data_path.name,
        "config_file": "runtime request",
        "xgboost_version": xgb.__version__,
        "python_version": sys.version,
    }

    report_payload = build_report_payload(
        global_df=global_df,
        schema=schema,
        sensitive_summary=sensitive_summary,
        stability_summary=stability_summary,
        fidelity_summary=fidelity_summary,
        permutation_summary=permutation_summary,
        additivity_summary=shap_result["additivity"],
        manifest_meta=manifest_meta,
        config=config,
        audit_sample_size=len(shap_result["ids"]),
        dataset_row_count=len(raw),
    )
    report_payload["limitations"] = summary["limitations"]
    write_json(output / "summary" / "report_payload.json", report_payload)
    summary["report"] = report_payload

    generated_files = [str(p.relative_to(output)) for p in sorted(output.rglob("*")) if p.is_file()]
    manifest = {**manifest_meta, "generated_files": generated_files}
    write_json(output / "metadata" / "audit_manifest.json", manifest)
    return summary
